name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to

    env:
      Project_Path: XsdTools\XsdTools.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Change working directory
      run: cd XsdTools
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build

    - name: Publish
      run: dotnet publish -c Release

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: XsdTools
        path: ${{ env.Project_Directory }}\XsdTools\bin\Release\net8.0\win-x64\publish
